In [ ]:
import numpy as np

## **1. ARRAYS**

**Basic Array creation**

In [ ]:
arr = np.array([1,2,3,4])
arr

In [ ]:
a = [1,2,3.5]
a

In [ ]:
np.array(a)

In [ ]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

In [ ]:
np.array(l)

**Array generation function**

In [ ]:
arr = np.arange(1,11,2)
arr

In [ ]:
arr = np.zeros((4,8))
arr

In [ ]:
arr = np.ones((6,6))
arr

In [ ]:
arr = np.linspace(0,1,100)
arr

**Random Generation function**

In [ ]:
np.random.rand(10)

In [ ]:
np.random.randn(10)

In [ ]:
np.random.randint(10,20,10)

**Array Attributes**

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

In [ ]:
arr.shape

In [ ]:
arr.size

In [ ]:
arr.dtype

**Array Methods**

In [ ]:
arr

In [ ]:
arr.min()

In [ ]:
arr.max()

In [ ]:
arr.sum()

In [ ]:
np.sum(arr,axis = 1)

In [ ]:
arr.mean()

In [ ]:
arr.std()

In [ ]:
arr.argmax()

In [ ]:
arr.argmin()

**Reshaping and resizing**

In [ ]:
arr = np.arange(1,31)
arr

In [ ]:
arr = arr.reshape(6,5)

In [ ]:
arr

**NUMPY INDEXING AND SLICING OF VECTORS**

In [ ]:
arr = np.arange(11,21)
arr

In [ ]:
arr_slice = arr[3::2]
arr_slice

In [ ]:
arr[4]

**NUMPY INDEXING AND SLICING OF MATRIX**

In [ ]:
arr = np.arange(1,31).reshape(6,5)
arr

In [ ]:
slice = arr[3:,3:]
slice

In [ ]:
arr[:,2]

**BOOLEAN INDEXING**

In [ ]:
arr = np.arange(11,21)
arr

In [ ]:
bool_index = arr %2 == 0
bool_index

In [ ]:
arr = arr[bool_index]
arr

## **2. ARRAY OPERATIONS**

*Arithmetic operations*

In [ ]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [ ]:
a1 + a2

In [ ]:
a1 -a2 

In [ ]:
a1 * a2

In [ ]:
a1 / a2

In [ ]:
a1 // a2

In [ ]:
a1 ** a2 

In [ ]:
arr2 *2

*Broadcasting*

In [ ]:
l = [10,20,30,40]
arr = np.array(l)

In [ ]:
arr + 10 

In [ ]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

In [ ]:
arr2 = arr2 + 10
arr2

*Deep and Shallow copy*

In [ ]:
a = np.arange(1,21)
a

In [ ]:
slice = a[:5]
slice = slice *10
slice

In [ ]:
a

In [ ]:
a[4:6] *10 

In [ ]:
a

In [ ]:
a
b = a.copy()

In [ ]:
b[0] = 99 

In [ ]:
b

In [ ]:
a

*Matrix operations*

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [ ]:
A

In [ ]:
B

In [2]:
A @ B

NameError: name 'A' is not defined

In [ ]:
np.dot(A,B)

In [ ]:
A

In [ ]:
A.T

**Advance Array Manipulation**

*Stacking Array*

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [ ]:
np.vstack((a,b))

In [ ]:
np.hstack((a,b))

In [ ]:
np.column_stack((a,b))

*Splitting array*

In [ ]:
c = np.arange(16).reshape(4, 4)
c

In [ ]:
np.hsplit(c,4)

In [ ]:
np.vsplit(c,2)

## **3. ARRAY INDEXING**

**NUMPY INDEXING AND SLICING OF VECTORS**

In [ ]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr_slice = arr[3::2]
arr_slice

array([14, 16, 18, 20])

In [ ]:
arr[4]

15

**NUMPY INDEXING AND SLICING OF MATRIX**

In [ ]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
slice = arr[3:,3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [ ]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

**BOOLEAN INDEXING**

In [ ]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
bool_index = arr %2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [ ]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])

## **4. Revision**

**Operations on Matrix & Vectors**

In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [ ]:
A

array([[1, 2],
       [3, 4]])

In [ ]:
B

array([[5, 6],
       [7, 8]])

In [ ]:
arr = np.arange(1,31,2).reshape(3,5)
arr

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29]])

In [ ]:
A * B #WRONG: as matrices are multipled as Dot product, not direct multiplication

array([[ 5, 12],
       [21, 32]])

In [ ]:
A @ B #Dot Product

array([[19, 22],
       [43, 50]])

In [ ]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [ ]:
A.T #Transpose

array([[1, 3],
       [2, 4]])

**Array Stacking - Only Applied on Vectors , Cant use Matricies**

In [ ]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
v3 = np.array([9,10,11,12])

In [ ]:
np.vstack((v2,v1,v3)) #joins Vertical by Specified Order

array([[ 5,  6,  7,  8],
       [ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [ ]:
np.hstack((v3,v1)) #joins in front by specifed order

array([ 9, 10, 11, 12,  1,  2,  3,  4])

In [ ]:
np.column_stack((v2,v3)) # joins in column

array([[ 5,  9],
       [ 6, 10],
       [ 7, 11],
       [ 8, 12]])

#### Shallow vs Deep Copy

-   **Shallow Copy**: Creates a new object, but populates it with *references* to the sub-objects found in the original. If you modify a mutable sub-object in the shallow copy, the original object will also be affected because they both refer to the same sub-object.
-   **Deep Copy**: Creates a new object and then, recursively, inserts *copies* into it of the sub-objects found in the original. Changes made to the deep copy do not affect the original object.

In [ ]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
new_arr = arr #Shallow Copy
new_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
new_arr[0] = 99
new_arr

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr #Affect Orignal Array

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
new_arr = arr.copy() #Depth Copy
new_arr

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
new_arr[9] = 70
new_arr

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 70])

In [ ]:
arr #No Affect on Orignal

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**Array Splitting**

In [ ]:
M1 = np.arange(16).reshape(4,4)
M1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
arr = np.hsplit(M1,2) #(array, no of splits) Horizontal Split
arr

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
arr[0]

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [ ]:
arr[1]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [ ]:
arr = np.hsplit(M1,3) #Error due to unequal divisions

ValueError: array split does not result in an equal division

In [ ]:
arr = np.hsplit(M1,4)
arr

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [ ]:
arr = np.vsplit(M1,2) #Vertical Split
arr

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [ ]:
arr = np.vsplit(M1,4)
arr

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

**Boolean Indexing**

In [ ]:
l = [1,2,3,4,5,6,7,8]
arr = np.array(l)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
bool_arr= arr%2==0
bool_arr

array([False,  True, False,  True, False,  True, False,  True])

In [ ]:
even_arr = arr[bool_arr]
even_arr

array([2, 4, 6, 8])

## **5. Exercise**

**Valid Sudoku**

In [ ]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [ ]:
r = np.sum(s, axis=1)
r

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [ ]:
for i in r:
  if i != 45:
    print(Suduko False for row)
    break
  else:
    print(Suduko True for row)

In [ ]:
c = np.sum(s, axis=0)
c == 45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [ ]:
for i in c:
  if i != 45:
    print("Suduko False for column")
    break
  else:
    print("Suduko True for column")

In [ ]:
 s[0:3,0:3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [ ]:
 s[0:3,3:6]

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [ ]:
for i in range(0,9,3):
  for j in range(0,9,3):
    matrix = s[i:i+3,j:j+3]
    print(matrix)

    matrix.sum()
    if matrix.sum() != 45:
      print("Suduko False for matrix")
      break
    else:
      print("Suduko True for matrix")



[[5 3 4]
 [6 7 2]
 [1 9 8]]
Suduko True for matrix
[[6 7 8]
 [1 9 5]
 [3 4 2]]
Suduko True for matrix
[[9 1 2]
 [3 4 8]
 [5 6 7]]
Suduko True for matrix
[[8 5 9]
 [4 2 6]
 [7 1 3]]
Suduko True for matrix
[[7 6 1]
 [8 5 3]
 [9 2 4]]
Suduko True for matrix
[[4 2 3]
 [7 9 1]
 [8 5 6]]
Suduko True for matrix
[[9 6 1]
 [2 8 7]
 [3 4 5]]
Suduko True for matrix
[[5 3 7]
 [4 1 9]
 [2 8 6]]
Suduko True for matrix
[[2 8 4]
 [6 3 5]
 [1 7 9]]
Suduko True for matrix


**General Questions**

In [ ]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [ ]:
#Get the shape of the matrix.

data.shape


(5, 3)

In [ ]:
#Find the average age of students.

age = data[:6,0]
age.mean()

np.float64(18.4)

In [ ]:
#Extract Math marks of all students.

mathmarks= data[:6,1]
mathmarks

array([85, 92, 76, 65, 90])

In [ ]:
#Find the highest Science mark.
score = data[:6,2]
score.max()

np.int64(95)

In [ ]:
#Get details of the student who scored more than 90 in Math.

std = mathmarks[mathmarks>90]
std


array([92])

In [ ]:
#Increase Math marks of all students by 5.
mathmarks = mathmarks + 5
mathmarks

array([90, 97, 81, 70, 95])

In [ ]:
#Find how many students are younger than 19.

age[age<19].size


3

In [ ]:
#Calculate the average marks in each subject (column-wise mean).

for i in range(1,3):
  print(data[:,i].mean())

81.6
83.2


In [ ]:
#Get data of students who scored at least 80 in both subjects.
std = data[(data[:,1]>=80) & (data[:,2]>=80)]
std

array([[19, 92, 88],
       [20, 90, 85]])

In [ ]:
#Replace all Science marks < 75 with 0.
data[:,2][data[:,2]<75] = 0
data


array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])